"""Detection signal functions for Provenance Guard.

Each signal takes raw submission text and returns a structured assessment
with a "score" in [0, 1], where 0 is strongly human-like and 1 is strongly
AI-like. The signals are intentionally different in kind so they capture
independent evidence rather than several versions of the same idea:

- llm_classification_score: a holistic judgment from a Groq LLM call.
- stylometric_score: surface statistics of an individual sentence
  (vocabulary diversity, punctuation, complexity, cliché phrasing).
- structural_repetition_score: repetition of multi-word structure ACROSS
  the whole text (repeated bigrams/trigrams and reused sentence openers) -
  a different property from the within-sentence surface stats above.

For the second content modality (image metadata rather than free text):

- metadata_provenance_score: reads structured image metadata (generator
  software tags, generation prompts, camera EXIF) for provenance evidence.
"""
import json
import os
import re
import statistics

from dotenv import load_dotenv
from groq import Groq

load_dotenv()


# --- Signal 1: LLM-based classification (Groq) ------------------------------

GROQ_MODEL = "llama-3.3-70b-versatile"

CLASSIFICATION_SYSTEM_PROMPT = (
    "You are an assistant that judges whether a piece of text was written by "
    "a human or generated by an AI language model. Consider semantic "
    "coherence, style, voice, and any tells that distinguish natural human "
    "writing from AI-generated text. Respond with strict JSON only, no extra "
    "commentary."
)

CLASSIFICATION_USER_PROMPT_TEMPLATE = """Read the text below and assess whether it was \
written by a human or generated by an AI.

Return ONLY a JSON object with this exact shape:
{{
  "score": <float 0.0-1.0, 0 = strongly reads as human-written, 1 = strongly reads as AI-generated>,
  "verdict": "<human|ai|uncertain>",
  "reasoning": "<one sentence explaining the judgment>"
}}

Text:
\"\"\"
{text}
\"\"\"
"""

_groq_client = None


def _get_groq_client() -> Groq:
    global _groq_client
    if _groq_client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set (check your .env file)")
        _groq_client = Groq(api_key=api_key)
    return _groq_client


def llm_classification_score(text: str) -> dict:
    """Signal 1: ask Groq to holistically judge human vs. AI authorship.

    Returns a structured assessment dict, e.g.:
    {
      "score": 0.78,
      "verdict": "ai",
      "reasoning": "..."
    }
    """
    client = _get_groq_client()

    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": CLASSIFICATION_SYSTEM_PROMPT},
            {"role": "user", "content": CLASSIFICATION_USER_PROMPT_TEMPLATE.format(text=text)},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )

    assessment = json.loads(response.choices[0].message.content)

    if "score" not in assessment:
        raise ValueError(f"Groq response missing 'score' field: {assessment!r}")

    assessment["score"] = _clamp(float(assessment["score"]))
    return assessment


# --- Signal 2: stylometric heuristics (pure Python) --------------------------

SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+")
WORD_RE = re.compile(r"[A-Za-z']+")
PUNCTUATION_RE = re.compile(r'[.,;:!?\-—()"]')

# Below this much text there isn't enough signal to trust the statistics at
# all, so we fall back to a flat neutral score. Low enough to admit a single
# short sentence rather than only multi-sentence submissions.
MIN_WORDS = 6

# A meaningful sentence-length *variance* requires comparing more than one
# sentence; below this we can't compute it at all, so it's left out of the
# average instead of being reported as a misleading extreme.
MIN_SENTENCES_FOR_VARIANCE = 2

# Type-token ratio is a length-dependent statistic: a short sample (e.g. one
# sentence) is almost always near-maximal vocabulary diversity regardless of
# who wrote it, since words rarely repeat within a single sentence at all.
# Below this many words it isn't a meaningful signal, so it's left out of
# the average instead of systematically dragging short text toward "human."
MIN_WORDS_FOR_TTR = 25

# Above the hard fallback floor, short text still makes these stats noisy
# (e.g. type-token ratio is mechanically higher on short samples regardless
# of authorship). Below this many words we don't fully trust the heuristic
# and pull the result toward neutral proportionally; at or above it the raw
# average is used as-is. Based on word count only, since sentence-count
# reliability is now handled per-metric (see MIN_SENTENCES_FOR_VARIANCE).
RELIABLE_WORDS = 80

# Calibration constants for the magnitude-based sub-scores. Heuristic and
# tunable: they cap "how much is a lot" for punctuation density and average
# sentence length before treating it as maximally AI-like. The punctuation
# cap is set generously (rather than e.g. 0.25) so that short, naturally
# punctuation-heavy prose (like terse human writing) doesn't immediately
# saturate the score.
PUNCTUATION_DENSITY_CAP = 0.35  # punctuation marks per word
SENTENCE_COMPLEXITY_CAP = 25.0  # words per sentence

# Phrases/words disproportionately common in LLM-generated text (transition
# clichés, hedge phrases, buzzwords). Vocabulary diversity (type-token
# ratio) can't catch this: a text can use entirely distinct words sentence
# to sentence and still be built almost entirely out of these stock phrases.
# This is a direct lexicon match, not a statistic about the text as a
# whole, but it's what actually operationalizes "unnatural phrase usage"
# from the original heuristic design.
CLICHE_PHRASES = [
    "it is important to note",
    "it is essential to",
    "it is crucial to",
    "in conclusion",
    "in summary",
    "paradigm shift",
    "delve into",
    "underscore the importance",
    "responsible deployment",
    "various stakeholders",
    "stakeholders across",
    "navigate the complexities",
    "fast-paced world",
    "ever-evolving landscape",
    "cutting-edge",
    "robust framework",
    "holistic approach",
    "leverage",
    "foster collaboration",
    "comprehensive overview",
    "multifaceted",
    "tapestry",
]

# Cliché-phrase hits per 100 words at/above which that sub-score saturates.
CLICHE_DENSITY_CAP = 3.0  # hits per 100 words

# Amplifies the raw average of the sub-scores around the 0.5 midpoint
# before reliability dampening is applied, so that text where the sub-scores
# already lean a direction reads as more clearly AI- or human-like instead of
# being compressed toward "uncertain." Applied before reliability dampening,
# which still pulls short text back toward neutral afterward.
STRETCH_FACTOR = 1.8


def stylometric_score(text: str) -> dict:
    """Signal 2: pure-Python stylometric heuristics.

    Combines measurable statistics that tend to differ between human and AI
    writing: sentence length variance, type-token ratio (vocabulary
    diversity), punctuation density, average sentence complexity, and
    cliché/buzzword phrase density. AI text tends to be more uniform and
    more reliant on stock phrasing; human writing tends to be more
    variable.

    Text shorter than MIN_WORDS falls back to a flat neutral score with no
    sub-scores at all, since nothing can be reliably computed. Above that,
    only sub-scores that are actually meaningful for the given text are
    computed and included: sentence length variance needs at least two
    sentences, and type-token ratio needs enough words to be more than
    noise. A sub-score that doesn't apply (e.g. sentence_length_variance on
    a single-sentence submission) is omitted from the result entirely
    rather than reported as a placeholder, so it can't dilute or mislead.

    The combined score is pulled toward neutral in proportion to word count
    (below RELIABLE_WORDS), since these statistics get noisier the shorter
    the sample.

    Returns a structured assessment dict, e.g.:
    {
      "score": 0.43,
      "sentence_length_variance_score": 0.6,
      "type_token_ratio_score": 0.3,
      "punctuation_density_score": 0.4,
      "sentence_complexity_score": 0.5
    }
    or, for a single short sentence where variance and TTR don't apply:
    {
      "score": 0.47,
      "punctuation_density_score": 0.4,
      "sentence_complexity_score": 0.5
    }
    """
    text = (text or "").strip()
    words = WORD_RE.findall(text)
    sentences = [s for s in SENTENCE_SPLIT_RE.split(text) if s.strip()]

    if len(words) < MIN_WORDS:
        return {"score": 0.5}

    sub_scores = {
        "punctuation_density_score": _punctuation_density_score(text, words),
        "sentence_complexity_score": _sentence_complexity_score(sentences),
    }
    cliche_hits = _cliche_phrase_hits(text)
    if cliche_hits > 0:
        # Zero hits isn't evidence of human writing, just an absence of this
        # particular tell, so it's only folded into the average when it
        # actually finds something - never lets a flat "no clichés" reading
        # drag a genuinely clean AI sample toward "human."
        sub_scores["cliche_phrase_score"] = _clamp(cliche_hits / len(words) * 100 / CLICHE_DENSITY_CAP)
    if len(words) >= MIN_WORDS_FOR_TTR:
        sub_scores["type_token_ratio_score"] = _type_token_ratio_score(words)
    if len(sentences) >= MIN_SENTENCES_FOR_VARIANCE:
        sub_scores["sentence_length_variance_score"] = _sentence_length_variance_score(sentences)

    raw_score = sum(sub_scores.values()) / len(sub_scores)
    stretched_score = 0.5 + (raw_score - 0.5) * STRETCH_FACTOR
    reliability = min(len(words) / RELIABLE_WORDS, 1.0)
    dampened_score = 0.5 + reliability * (stretched_score - 0.5)

    return {
        "score": _clamp(round(dampened_score, 4)),
        **sub_scores,
    }


def _sentence_length_variance_score(sentences: list) -> float:
    if len(sentences) < MIN_SENTENCES_FOR_VARIANCE:
        return 0.5
    lengths = [len(WORD_RE.findall(s)) for s in sentences]
    mean_len = statistics.mean(lengths)
    if mean_len == 0:
        return 0.5
    coefficient_of_variation = statistics.pstdev(lengths) / mean_len
    # Low variation in sentence length reads as more AI-like (more uniform).
    return _clamp(1 - coefficient_of_variation)


def _type_token_ratio_score(words: list) -> float:
    lowered = [w.lower() for w in words]
    type_token_ratio = len(set(lowered)) / len(lowered)
    # Low vocabulary diversity reads as more AI-like (more repetitive wording).
    return _clamp(1 - type_token_ratio)


def _punctuation_density_score(text: str, words: list) -> float:
    punctuation_count = len(PUNCTUATION_RE.findall(text))
    density = punctuation_count / len(words)
    return _clamp(density / PUNCTUATION_DENSITY_CAP)


def _sentence_complexity_score(sentences: list) -> float:
    lengths = [len(WORD_RE.findall(s)) for s in sentences]
    mean_complexity = statistics.mean(lengths)
    return _clamp(mean_complexity / SENTENCE_COMPLEXITY_CAP)


def _cliche_phrase_hits(text: str) -> int:
    lowered = text.lower()
    return sum(lowered.count(phrase) for phrase in CLICHE_PHRASES)


def _clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, value))


# --- Signal 3: structural repetition & burstiness (pure Python) --------------
#
# Where the stylometric signal looks at *within-text vocabulary* (unigram
# type-token ratio, punctuation, sentence complexity), this signal looks at
# repetition of multi-word *structure* across the whole submission: the same
# two- and three-word sequences recurring, and sentences that keep opening the
# same way ("Additionally,", "Moreover,", "The ..."). AI text tends to reuse
# phrase- and clause-level scaffolding even when its individual word choices
# are varied, so a text can pass the unigram diversity check and still be
# highly repetitive at this level. Genuinely different evidence, not a second
# flavour of Signal 2.

# N-gram repetition needs a few sentences of material to mean anything; below
# this, gaps are omitted from the sub-score set rather than reported as an
# extreme. Openers need at least this many sentences to compare.
MIN_SENTENCES_FOR_OPENERS = 3


def structural_repetition_score(text: str) -> dict:
    """Signal 3: phrase- and structure-level repetition across the text.

    Combines three sub-scores, each in [0, 1] and higher = more AI-like:

    - bigram_repetition_score: fraction of two-word sequences that are
      repeats. Templated text reuses the same short phrases.
    - trigram_repetition_score: same, for three-word sequences.
    - opener_repetition_score: fraction of sentences that start with a
      first-word already used to open an earlier sentence.

    A sub-score is only included when the text is long enough for it to be
    meaningful (n-grams need enough tokens; openers need several sentences),
    matching Signal 2's policy of omitting rather than faking a metric. The
    result is dampened toward neutral for short text via the same
    RELIABLE_WORDS ramp used by the stylometric signal, so the three signals
    treat "not enough text to be sure" consistently.
    """
    text = (text or "").strip()
    words = [w.lower() for w in WORD_RE.findall(text)]
    sentences = [s for s in SENTENCE_SPLIT_RE.split(text) if s.strip()]

    if len(words) < MIN_WORDS:
        return {"score": 0.5}

    sub_scores = {}
    if len(words) >= 4:
        sub_scores["bigram_repetition_score"] = _ngram_repetition_score(words, 2)
        sub_scores["trigram_repetition_score"] = _ngram_repetition_score(words, 3)
    if len(sentences) >= MIN_SENTENCES_FOR_OPENERS:
        sub_scores["opener_repetition_score"] = _opener_repetition_score(sentences)

    if not sub_scores:
        return {"score": 0.5}

    raw_score = sum(sub_scores.values()) / len(sub_scores)
    stretched_score = 0.5 + (raw_score - 0.5) * STRETCH_FACTOR
    reliability = min(len(words) / RELIABLE_WORDS, 1.0)
    dampened_score = 0.5 + reliability * (stretched_score - 0.5)

    return {
        "score": _clamp(round(dampened_score, 4)),
        **{k: round(v, 4) for k, v in sub_scores.items()},
    }


def _ngram_repetition_score(words: list, n: int) -> float:
    ngrams = [tuple(words[i:i + n]) for i in range(len(words) - n + 1)]
    if not ngrams:
        return 0.5
    repetition = 1 - (len(set(ngrams)) / len(ngrams))
    # Repetition is naturally small even for AI text, so amplify: treat a
    # third of n-grams repeating as maximally AI-like.
    return _clamp(repetition / 0.33)


def _opener_repetition_score(sentences: list) -> float:
    openers = []
    for s in sentences:
        first = WORD_RE.findall(s)
        if first:
            openers.append(first[0].lower())
    if not openers:
        return 0.5
    repetition = 1 - (len(set(openers)) / len(openers))
    return _clamp(repetition / 0.5)


# --- Modality 2 signal: image metadata provenance ---------------------------
#
# The second content type is structured image metadata rather than free text
# (see planning.md's Multi-modal note). This signal reads provenance evidence
# straight out of the metadata dict: which software wrote the file, whether a
# generation prompt is present, and whether camera-capture EXIF exists. It is
# a genuinely different modality with its own tells, so it gets its own signal
# rather than being forced through the text heuristics. The image's caption,
# if present, is still analysed by the text signals separately (see service).

# Substrings in software/tool/generator fields that indicate AI generation.
AI_GENERATOR_TAGS = [
    "stable diffusion", "stablediffusion", "midjourney", "dall-e", "dall e",
    "dalle", "adobe firefly", "firefly", "imagen", "flux", "comfyui",
    "automatic1111", "invokeai", "leonardo.ai", "leonardo ai", "novelai",
    "gan", "diffusion", "generated by ai", "ai-generated", "ai generated",
]

# Metadata keys that describe camera capture. Their presence is evidence of a
# real photograph; their total absence is (weak) evidence of synthesis.
CAMERA_EXIF_KEYS = [
    "make", "model", "lens", "lensmodel", "exposuretime", "fnumber",
    "aperture", "iso", "isospeedratings", "focallength", "gps", "gpslatitude",
    "datetimeoriginal", "shutterspeedvalue",
]

# Keys whose mere presence signals AI generation (prompt-driven synthesis).
GENERATION_PARAM_KEYS = [
    "prompt", "negative_prompt", "negativeprompt", "sampler", "cfg_scale",
    "cfgscale", "steps", "seed", "model_hash", "modelhash", "scheduler",
]

SOFTWARE_KEYS = ["software", "generator", "creatortool", "creator_tool",
                 "processing_software", "processingsoftware", "tool", "app"]


def metadata_provenance_score(metadata: dict) -> dict:
    """Modality-2 signal: judge AI generation from structured image metadata.

    Returns {"score", "verdict", "reasoning", "indicators"} where score is in
    [0, 1] (1 = strongly reads as AI-generated). Weighs three kinds of
    evidence: AI-generator software tags and generation parameters push toward
    AI; rich camera EXIF pulls toward human capture; a bare metadata block
    with no capture evidence leans mildly AI.
    """
    if not isinstance(metadata, dict):
        metadata = {}

    lowered = {str(k).lower(): str(v).lower() for k, v in metadata.items()}
    indicators = []

    ai_software = False
    for key in SOFTWARE_KEYS:
        value = lowered.get(key, "")
        if any(tag in value for tag in AI_GENERATOR_TAGS):
            ai_software = True
            indicators.append(f"AI generator tag in '{key}': {value!r}")

    gen_params = [k for k in GENERATION_PARAM_KEYS if k in lowered]
    if gen_params:
        indicators.append(f"generation parameters present: {sorted(gen_params)}")

    camera_keys = [k for k in CAMERA_EXIF_KEYS if k in lowered and lowered[k]]
    if camera_keys:
        indicators.append(f"camera EXIF present: {sorted(camera_keys)}")

    # Start neutral and move on evidence. Software tags and generation params
    # are strong; camera EXIF is the main counter-evidence.
    score = 0.5
    if ai_software:
        score += 0.4
    if gen_params:
        score += 0.25 if not gen_params[1:] else 0.35
    if camera_keys:
        score -= 0.1 * min(len(camera_keys), 4)  # up to -0.4 for a full EXIF block
    elif not ai_software and not gen_params:
        # No capture provenance and no generation evidence either: a bare,
        # stripped metadata block. Mildly suspicious, but far from conclusive.
        score += 0.1
        indicators.append("no camera EXIF and no generation params (stripped metadata)")

    score = _clamp(round(score, 4))
    if score >= 0.56:
        verdict = "ai"
    elif score <= 0.44:
        verdict = "human"
    else:
        verdict = "uncertain"

    if not indicators:
        indicators.append("no decisive provenance markers in metadata")

    return {
        "score": score,
        "verdict": verdict,
        "reasoning": "; ".join(indicators),
        "indicators": indicators,
    }
